### ISSUE TITLE
Playbook not install env file

### ISSUE THREAD

**Issue by dragonflame** [mother-of-all-self-hosting/ansible-role-firezone#1]
Hi.
Trying to install with MASH playbook and found error - in file tasks/install.yml (task **Ensure Firezone support files installed**) .
not used `{{ item }} ` var in `src` and `dest` parameters, so only **labels** file created.
Thus, after that firezone service fail with error about **env** file. 
Additionally after correct **env** file creation, folder rights  for **data** folder (mounted to **/var/firezone** inside container) not enough for writing certificate files.
And only after fixing that problem target service can start.

**Comment by moan0s** [comment]
Thanks for the report! 
First one will be fixed in a sec
Which permission works for you? It is currently `755` for me and works but maybe it needs to be something else to install. It would be ideal to have an error message

**Comment by moan0s** [comment]
Ahhhh I remember - we currently can't use
```
--user 998:1000 \
```
as there still is [an upstream bug](https://github.com/moan0s/role-firezone/issues/2)
The short term solution would be to set the folder to `777` (not recommended for security reasons)

**Comment by moan0s** [comment]
Fixed with e0bd45abf946cd9bf263fabafa64350cd0c48592 (env file) and 34b383fa896319d21fff49617df44b42b543d904 (permission issue). Implementation with `--user` safer variant will be tracked in #2
